installed tailwind and updated styles
swfl-coders/tech-alliance-website pull request #61
Opened 2024-09-17 21:04 UTC by jonathans199

2024-09-18 00:35 UTC, zarela commented on tailwind.config.js
> +}
Missing end of line

2024-09-18 00:36 UTC, zarela requested changes
Requested a tiny change, just an end of line, but also since I merged prettier, you have to update your branch and solve the merge conflicts. Thank you! 😃

2024-09-23 22:57 UTC, allantito commented
@jonathans199

2024-09-23 23:12 UTC, jonathans199 commented
@zarela when you have a chance can you please update your repo locally and maybe overwrite the `package-lock.json` the are 43 conflicts, which will take real long to fix. 

So as long as it runs on your computer you could push up the working version, I don't have access to push directly. 

Thank you, let me know any questions.

2024-09-25 19:50 UTC, zarela commented
@jonathans199 
I can't override the lock file because we need your new version which is introducing the new package, even if I override you will have a conflict again. What we could do is you delete all your changes for the package-lock file so there are not conflicts there and I can generate a new lock file once your PR is merged

2024-09-27 21:32 UTC, jonathans199 commented
Closing this merge to main directly, creating a new branch to merge in to staging.

2024-09-27 21:32 UTC, closed without merging